name: healingapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.5+5

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17
  connectivity_plus: ^3.0.4
  flutter_inappwebview: 5.7.2+3
  flutter_native_splash: ^2.2.17
  url_launcher: ^6.1.8
  path_provider: ^2.0.12
  store_redirect: ^2.0.1
  change_app_package_name: ^1.1.0
  flutter_downloader: ^1.10.4
  permission_handler: ^10.3.0
  flutter_launcher_icons: ^0.13.1
  animate_do: ^3.0.2
  flutter_local_notifications: ^13.0.0
  firebase_core: 2.14.0
  # firebase_messaging: 14.6.4
  audio_session: 
  just_audio_background:
  just_audio:
  get: 4.6.5
  firebase_ui_database: 1.2.0
  firebase_database: ^10.2.3
  cloud_firestore: ^4.8.2
  story_view: ^0.14.0
  sleek_circular_slider: ^2.0.1
  cached_network_image: ^3.2.3
  palette_generator: ^0.3.3+2
  flutter_dnd: ^0.1.4+1
  marquee: ^2.2.3

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios:
  color: "#102e37"
  image_path: "assets/images/play_store_512.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


flutter_native_splash:  
  color: "#102e37"
  andriod: true
  ios: true
  andriod_gravity: centre
  # fill: tru:
  fullscreen: true
  ios_content_mode: scaleAspectFill
  web: false

flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf
    - family: Andina
      fonts:
        - asset: assets/fonts/andina.ttf
